import * as HeroIcons from '@heroicons/react/24/outline';

export const SERVICE_ICONS = [
  { name: 'map-pin', label: 'Map Pin', icon: HeroIcons.MapPinIcon },
  { name: 'document-text', label: 'File / Docs', icon: HeroIcons.DocumentTextIcon },
  { name: 'eye', label: 'Eye / View', icon: HeroIcons.EyeIcon },
  { name: 'arrow-trending-up', label: 'Trending Up', icon: HeroIcons.ArrowTrendingUpIcon },
  { name: 'home-modern', label: 'Home Modern', icon: HeroIcons.HomeModernIcon },
  { name: 'home', label: 'Home', icon: HeroIcons.HomeIcon },
  { name: 'building-office', label: 'Office', icon: HeroIcons.BuildingOfficeIcon },
  { name: 'building-storefront', label: 'Store', icon: HeroIcons.BuildingStorefrontIcon },
  { name: 'key', label: 'Key', icon: HeroIcons.KeyIcon },
  { name: 'lock-closed', label: 'Security', icon: HeroIcons.LockClosedIcon },
  { name: 'map', label: 'Map', icon: HeroIcons.MapIcon },
  { name: 'globe-alt', label: 'Global', icon: HeroIcons.GlobeAltIcon },
  { name: 'currency-dollar', label: 'Finance', icon: HeroIcons.CurrencyDollarIcon },
  { name: 'banknotes', label: 'Cash', icon: HeroIcons.BanknotesIcon },
  { name: 'credit-card', label: 'Payment', icon: HeroIcons.CreditCardIcon },
  { name: 'chart-bar', label: 'Stats', icon: HeroIcons.ChartBarIcon },
  { name: 'chart-pie', label: 'Analytics', icon: HeroIcons.ChartPieIcon },
  { name: 'calculator', label: 'Calculator', icon: HeroIcons.CalculatorIcon },
  { name: 'scale', label: 'Legal', icon: HeroIcons.ScaleIcon },
  { name: 'shield-check', label: 'Verified', icon: HeroIcons.ShieldCheckIcon },
  { name: 'check-badge', label: 'Quality', icon: HeroIcons.CheckBadgeIcon },
  { name: 'sparkles', label: 'Premium', icon: HeroIcons.SparklesIcon },
  { name: 'star', label: 'Rating', icon: HeroIcons.StarIcon },
  { name: 'heart', label: 'Loved', icon: HeroIcons.HeartIcon },
  { name: 'user', label: 'User', icon: HeroIcons.UserIcon },
  { name: 'user-group', label: 'Community', icon: HeroIcons.UserGroupIcon },
  { name: 'users', label: 'Team', icon: HeroIcons.UsersIcon },
  { name: 'phone', label: 'Contact', icon: HeroIcons.PhoneIcon },
  { name: 'envelope', label: 'Email', icon: HeroIcons.EnvelopeIcon },
  { name: 'chat-bubble-left-right', label: 'Chat', icon: HeroIcons.ChatBubbleLeftRightIcon },
  { name: 'megaphone', label: 'Marketing', icon: HeroIcons.MegaphoneIcon },
  { name: 'bell', label: 'Alerts', icon: HeroIcons.BellIcon },
  { name: 'calendar', label: 'Schedule', icon: HeroIcons.CalendarIcon },
  { name: 'clock', label: 'Time', icon: HeroIcons.ClockIcon },
  { name: 'wrench', label: 'Tools', icon: HeroIcons.WrenchIcon },
  { name: 'cog-6-tooth', label: 'Settings', icon: HeroIcons.Cog6ToothIcon },
  { name: 'camera', label: 'Photos', icon: HeroIcons.CameraIcon },
  { name: 'video-camera', label: 'Video', icon: HeroIcons.VideoCameraIcon },
  { name: 'photo', label: 'Gallery', icon: HeroIcons.PhotoIcon },
  { name: 'cube', label: '3D Model', icon: HeroIcons.CubeIcon },
  { name: 'paint-brush', label: 'Design', icon: HeroIcons.PaintBrushIcon },
  { name: 'scissors', label: 'Craft', icon: HeroIcons.ScissorsIcon },
  { name: 'light-bulb', label: 'Idea', icon: HeroIcons.LightBulbIcon },
  { name: 'bolt', label: 'Fast', icon: HeroIcons.BoltIcon },
  { name: 'fire', label: 'Hot', icon: HeroIcons.FireIcon },
  { name: 'truck', label: 'Logistics', icon: HeroIcons.TruckIcon },
  { name: 'sun', label: 'Day', icon: HeroIcons.SunIcon },
  { name: 'moon', label: 'Night', icon: HeroIcons.MoonIcon },
  { name: 'cloud', label: 'Cloud', icon: HeroIcons.CloudIcon },
  { name: 'arrows-pointing-out', label: 'Expand', icon: HeroIcons.ArrowsPointingOutIcon },
  { name: 'check-circle', label: 'Check', icon: HeroIcons.CheckCircleIcon },
  { name: 'information-circle', label: 'Info', icon: HeroIcons.InformationCircleIcon },
];
